# Generated by Django 3.1.5 on 2021-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000, null=True)),
                ('specialization', models.TextField(max_length=1000, null=True)),
                ('location', models.TextField(max_length=1000, null=True)),
                ('telephone_number', models.TextField(max_length=1000, null=True)),
                ('website', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000, null=True)),
                ('location', models.TextField(max_length=1000, null=True)),
                ('telephone_number', models.TextField(max_length=100, null=True)),
                ('website', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
